ktor:
  application:
    modules:
      - com.example.plugins.ApplicationKt.module
  deployment:
    port: 8080

postgres:
  user: "postgres"
  password: "admin"
  host: "localhost"
  port: "5432"
  name: "socialapp"

jwt:
  audience: "users"
  domain: "https://jwt-provider-domain/"
  realm: "ktor sample app"
  secret: "secret"
